### ISSUE TITLE
Cannot install into VS 2022

### ISSUE THREAD

**Issue by mtanneryd-marketmath** [sjh37/efreversepoco#728]
Running the vsix file for 3.4.1 I do not get the option to install on my VS 2022 installation. What am I doing wrong?

**Comment by sjh37** [comment]
I will be making a release this week to support VS 2022

**Comment by mtanneryd** [comment]
Looking forward to that! Thank you!

**Comment by pierrebrito** [comment]
> I will be making a release this week to support VS 2022

Hellow!

Is it already available for .NET6?

**Comment by sjh37** [comment]
Almost. If you set the generator to create .net 5 code, the compiler will tell you what to implement on the fake db context that is used for unit testing on .net 6.
