### ISSUE TITLE
Support for EF Core 6

### ISSUE THREAD

**Issue by JustinasKilas** [sjh37/efreversepoco#732]
Is there so scheduled release for .NET 6 EF Core 6 support?

**Comment by sjh37** [comment]
It's on the cards. It _almost_ works right out of the box if you specify EF Core 5. Just one interface tweak on the Fake db context.

**Comment by JustinasKilas** [comment]
Yup tweaked it to generate code without errors and it seems to work fine

**Comment by pierrebrito** [comment]
Hi, is there any release date?

**Comment by sjh37** [comment]
Coding is complete and currently being regression tested. Release will be in February.

**Comment by sjh37** [comment]
Now released in v3.6.0
