### ISSUE TITLE
Warning SP returns multiple return sets, but in reality, it only returns one 

### ISSUE THREAD

**Issue by MarkLFT** [sjh37/efreversepoco#734]
When I try to include a few stored procedures, I receive the message Cannot be created as EF does not support multiple return sets, but when I execute the SP, only one is being returned. 

The issue seems to be because I have a final clause in the sp and select accordingly. For example:

if @ExcludeDuplicates = 1
Begin
  Select ........
End
Else
Begin
  Select .....
End

Both selects return identical record sets, the only difference being the data rows included/excluded.

I understand from other posts, that you do not parse the SP ,and just use the SET FMTONLY ON; to get the return sets, but as they are return identical return sets, and actually only one is ever performed, I am confused when we get this?  Any ideas you can think of on how to work around this?  That does not involve me re-writing a number of SP's?

**Comment by sjh37** [comment]
Hi Mark.
There are several tickets for this already, in various guises. I need to find a good solution for this and other cases listed below.
- #37
- #81
- #95
- #265
- #620

Select the data into a variable within each select statement.
```sql
AS
BEGIN
	SET NOCOUNT ON;
	SET XACT_ABORT ON;

	DECLARE @ExpiresUtc DATETIME 

	IF @IncludeFreeTrial = 0
	BEGIN
		SELECT @ExpiresUtc = GETDATE(); -- Use your SQL
	END
	ELSE
	BEGIN
		SELECT @ExpiresUtc = GETDATE() + 100;  -- Use your SQL
	END
	SELECT @ExpiresUtc AS ExpiresUtc; -- Return a single result set
END
```

That will return a single result set back.

**Comment by MarkLFT** [comment]
Thanks for the confirmation of what I had guessed, I have to now rewrite a lot of SP's.  Which all unfortunately return record sets not simple values as in your example.
