### ISSUE TITLE
The store type 'bigint' could not be found in the Npgsql provider manifest

### ISSUE THREAD

**Issue by uyau** [sjh37/efreversepoco#736]
The same error for "integer" and date "timestamp without time zone" and maybe more, i didn't go further. Why so, if database have this types?

**Comment by uyau** [comment]
Found table with types that allows rewrite the table cofiguration. Bigint will be int8. integer - int4. 
after replacing HasColumnType() with that types all work fine.
https://www.postgresql.org/docs/8.1/datatype.html

**Comment by sjh37** [comment]
Thanks @uyau I'll make sure this gets corrected for the next release.

**Comment by uyau** [comment]
also small int goes like "int2" and "timestamp without time zone" just "timestamp". Thats all problem types that I had issue with.
4 types. Maybe there can be some more, but not in my db) Don't have time to sit and test it out)

**Comment by sjh37** [comment]
Can you post the `PostgresToCSharp` C# file here that you modified so I can see what you changed 👍

**Comment by sjh37** [comment]
@uyau  in your `<database>.tt` file, approx line 14, do you have your Settings.Database set to PostgreSQL?
```c#
Settings.DatabaseType = DatabaseType.PostgreSQL;
```

**Comment by uyau** [comment]
@sjh37 I had follow your instruction by installing msi into GAC, after I installed pacage EntityFramework6.Npgsql with that comes all other packages needed like Npgqls and EF...
Then I set settings in tt:
Settings.DatabaseType = DatabaseType.PostgreSQL;
Settings.TemplateType = TemplateType.Ef6;
Settings.GeneratorType = GeneratorType.Ef6;
Settings.GenerateSeparateFiles = true;
And adding connection string in my web.config

Aftet I save tt. And try to run application. First errors to fix:
In generated "MyDbContext.cs" class I have to change  
line - 86 "public bool IsSqlParameterNull(NpgsqlParameter param)" to NpgsqlParameter (or maybe add using npgsql, don't remember)
and line 88 "var sqlValue = param.SqlValue;" to param.NpgsqlValue

Then I run application and in first linq I have error with bigint. Next I open every tableConfiguration and  in lines like:
Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int4").IsRequired()    I'm changing "HasColomnType" to int8,int4, int2 and timezone like I sad earlyer. And after that everything works fine for me) That's all steps I did. Nothing more)

**Comment by uyau** [comment]
This solution worked for .net Framework 4.5 and 4.7. Same sequence in both case

**Comment by GFoley83** [comment]
>Aftet I save tt. And try to run application. First errors to fix:
In generated "MyDbContext.cs" class I have to change
line - 86 "public bool IsSqlParameterNull(NpgsqlParameter param)" to NpgsqlParameter (or maybe add using npgsql, don't remember)
and line 88 "var sqlValue = param.SqlValue;" to param.NpgsqlValue

Thank you @uyau. This fixed my error with a brand new solution using EF7 Core and .NET Core for PostgreSQL. Definitely a bug that needs to be fixed.

**Comment by sjh37** [comment]
This has been released in v3.8.2. Any problems, please let me know.

**Comment by sjh37** [comment]
1. `PostgreSqlDatabaseReader` SQL queries `INFORMATION_SCHEMA.COLUMNS.DATA_TYPE`, which returns standard PostgreSQL names: bigint, integer, smallint, timestamp without time zone
  2. `DatabaseReader.cs` sets `SqlPropertyType = rt.TypeName` — the raw value, no translation
  3. `GeneratorEfCore.cs` writes `.HasColumnType("bigint")` etc. directly from SqlPropertyType

  The core question is: Does Npgsql's EF Core provider manifest accept those standard names?

  The answer: **yes**, in Npgsql 4.x and later — the provider manifest accepts both the standard PostgreSQL names (bigint, integer, timestamp without time zone) and the short aliases (`int8`, `int4`, `timestamp`). The original reporter was using an older Npgsql 3.x with EF6, where only short aliases were accepted.
