### ISSUE TITLE
Status on mysql?

### ISSUE THREAD

**Issue by nielshenriksen** [sjh37/efreversepoco#742]
What is status on mysql?

**Comment by sjh37** [comment]
Sorry for the delay. The SQL to reverse engineer needs to be created for MySQL. Everything else is in place. Same goes for Oracle.
The next release in the comming week will add EFCore 6 support. A few enhancements to the website, then nothing else would be in the way in adding support for mysql.

**Comment by nielshenriksen** [comment]
thats super :)

**Comment by sjh37** [comment]
I've finished V4 of the Entity Framework Reverse Poco Generator. I've not released it yet and wanted a few select people to try it out first. It now supports SQL Server, Oracle, MySQL, PostgreSQL and SQLite. Would you like to try it out before the official release?

It now comes in two parts:
 - dotnet tool install -g Efrpg
 - Download the v4 vsix from https://reversepocostorage.blob.core.windows.net/public-file-share/EFRPG_Generator_v4.vsix
 - Upgrade guide https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/Upgrading-from-v3-to-v4
