### ISSUE TITLE
Namespace not generating correctly

### ISSUE THREAD

**Issue by pomistea** [sjh37/efreversepoco#743]
Hi-

I'm currently using the same settings as I used with v2.32 and the namespace generates fine, there.
I've a licence for v2.32 and I'm using a trial licence with v3.5
Namespace generates with a new random number every time, something like this:

**namespace Microsoft.VisualStudio.TextTemplatingAB0EB7BB95379970726990CDD3231A48F3797E62E8022B3AD0DE8D94A1B6ADF24521E2771328BCF8F95CD6DC7BDB8922E250C272D00DBA175BEAB81C629496B1**

Settings:
------------------
    Settings.ElementsToGenerate = Elements.Poco | Elements.Context | Elements.Interface | Elements.PocoConfiguration | Elements.Enum;

    Settings.PocoNamespace              = ""; // "YourProject.Entities";
    Settings.InterfaceNamespace         = ""; // "YourProject.Interfaces";
    Settings.PocoConfigurationNamespace = ""; // "YourProject.Configuration";

**Comment by sjh37** [comment]
Strangly I have seen this before, however I can't repeat it.
Force the correct value by setting the following value in your `<database>.tt` file.

```c#
Settings.Namespace = "your.namespace,here";
```

**Comment by pomistea** [comment]
That worked, beautiful!.
Settings.Namespace, who knew 😀

Thank you for such a quick response, have a good weekend 🙂
