### ISSUE TITLE
.HasName is obsolete: Use HasDatabaseName() instead

### ISSUE THREAD

**Issue by dlubart** [sjh37/efreversepoco#745]
I am on .Net Core 6 with latest updates.  v3.6.0 of the TT include file.

My indexes all generate this warning in the .cs file (which I know has been a previous issue that you indicated was fixed a while back).

Warning	CS0618	'RelationalIndexBuilderExtensions.HasName<TEntity>(IndexBuilder<TEntity>, string?)' is obsolete: 'Use HasDatabaseName() instead.'

It doesn't seem to interfere with anything but is there anything I might be doing that is causing it that I can remediate?

Thanks.

**Comment by sjh37** [comment]
It does use `HasDatabaseName` if

```cs
Settings.TemplateType = TemplateType.EfCore6;
```

Can you check what settings you are using in your `<database>.tt` file

**Comment by dlubart** [comment]
It was at .EfCore3.  I raised to EfCore6 and got an error:

-  Compiling transformation: 'GeneratedTextTransformation.TemplateType' does not contain a definition for 'EfCore6'	

I set it back to EfCore5 and it seems to be okay.  Should EfCore6 work as well?

**Comment by sjh37** [comment]
The `TemplateType` enum inside `EF.Reverse.POCO.v3.ttinclude` should look like this:

```cs
public enum TemplateType
{
    Ef6,
    EfCore2,
    EfCore3,
    EfCore5,
    EfCore6,
    FileBasedCore2,
    FileBasedCore3,
    FileBasedCore5,
    FileBasedCore6
}
```

Can you please check.
Grab the latest .ttinclude file from here [EF.Reverse.POCO.v3.ttinclude](https://raw.githubusercontent.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/master/EntityFramework.Reverse.POCO.Generator/EF.Reverse.POCO.v3.ttinclude)

**Comment by dlubart** [comment]
This is the issue.  I have 3.6.0 of the ttinclude file, but my enum is this:

`    public enum TemplateType
    {
        Ef6,
        EfCore2,
        EfCore3,
        EfCore5,
        FileBasedCore2,
        FileBasedCore3,
        FileBasedCore5
    }`

Was this updated without a version change somehow?  I can pull the latest file in but I just did this on 12/23 and thought I had the latest at that time.

**Comment by sjh37** [comment]
You probably pulled in the latest code from github before I had officially released it. I will close this issue.
