### ISSUE TITLE
Error: Cannot insert an explicit value into a timestamp column

### ISSUE THREAD

**Issue by nealculiner** [sjh37/efreversepoco#753]
I'm trying to add a new entity in EF Core 5 and I'm getting an error due to a column that has a time stamp data type (nullable). The error returned is:

> Cannot insert an explicit value into a timestamp column

I think what's missing in the generator for a timestamp column per a google search on this error is it possibly needs:

`.ValueGeneratedOnAddOrUpdate();`

Before:

`builder.Property(x => x.ts).HasColumnName(@"ts").HasColumnType("timestamp").IsRequired(false);`

After:

`builder.Property(x => x.ts).HasColumnName(@"ts").HasColumnType("timestamp").IsRequired(false).ValueGeneratedOnAddOrUpdate();`

https://entityframeworkcore.com/knowledge-base/45825877/inserting-record-in-sql-table-with-timestamp-datatype

**Comment by nealculiner** [comment]
Adding the .ValueGeneratedOnAddOrUpdate(); resolved my issue. I'd offer this is a critical/blocker issue

**Comment by sjh37** [comment]
Thanks Neal, I'll get this added.

**Comment by nealculiner** [comment]
Any timeline when we'll get an update for this? I really need this fixed ASAP please. I believe this affects RowVersion column types too.

**Comment by nealculiner** [comment]
I think the generator is missing the .IsRowVersion() method on this column type when it's set to required.

**Comment by sjh37** [comment]
Hi @nealculiner Looking into now.

**Comment by sjh37** [comment]
Created wiki article https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/RowVersion-and-TimeStamp-columns

**Comment by sjh37** [comment]
Got it sorted @nealculiner. Thanks for your patience.

Grab the latest code from [EF.Reverse.POCO.v3.ttinclude](https://raw.githubusercontent.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/master/EntityFramework.Reverse.POCO.Generator/EF.Reverse.POCO.v3.ttinclude) and replace your project file with it.

Any problems, give me a shout.

**Comment by nealculiner** [comment]
Thank you

**Comment by nealculiner** [comment]
@sjh37 did you commit your changes as I don't see anything different yet?

**Comment by sjh37** [comment]
Sorry my bad, It's on the `development` branch.
Here it is [development/EF.Reverse.POCO.v3.ttinclude](https://raw.githubusercontent.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/2544fa7b2ad90dabbd7b228288960e8ae552b242/EntityFramework.Reverse.POCO.Generator/EF.Reverse.POCO.v3.ttinclude)

**Comment by sjh37** [comment]
Now released in 3.6.1
