### ISSUE TITLE
Settings.ConnectionString vs Settings.ConnectionStringName

### ISSUE THREAD

**Issue by kurt-o-matic** [sjh37/efreversepoco#759]
Sorry to open an issue on this, but I'm having trouble with the connection string configuration. I'm using V3.6.0 with EFCore/.NET 6.

The Settings.ConnectionString value is working great, no problems running the generator. However, the resulting generated code includes the literal value of this connection string hard-coded into the context's OnConfiguring method, which is completely inappropriate. The Settings.ConnectionStringName value I provided does not appear anywhere in the generated code, including the context constructor, as stated in the template comments. The template comments imply that the generator will include the configuration connection string lookup in the context constructor, but I'm not seeing anything like that.

What am I missing? How should a bog-standard asp.net/ef core appsettings.config be integrated with the reverse-engineered context for connection strings? How do I keep hard-coded connection strings out of my source repo (aside from the template itself)?

**Comment by sjh37** [comment]
Hi. Have a read of https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/ConnectionString

And this page https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/Settings.OnConfiguration

I would say you need to set `Settings.OnConfiguration = OnConfiguration.Configuration`

**Comment by kurt-o-matic** [comment]
Thanks, Simon! I knew I was missing something; Settings.OnConfiguration is exactly what I needed. 👍
