### ISSUE TITLE
Error: No suitable method found to override: GetAsyncEnumerator in FakeDbSet

### ISSUE THREAD

**Issue by slee-accesso** [sjh37/efreversepoco#763]
Hi Simon - hope you're well,

I just upgraded to 3.6 recently. The generated FakeDbSet.cs code leaves me with this error:

```
CS0115 'FakeDbSet<TEntity>.GetAsyncEnumerator(CancellationToken)': no suitable method found to override
```
Commenting out the code makes it compile, Should I worry about this? Should we remove this code from the .ttinclude?

Code that I commented out:
```csharp
public override IAsyncEnumerator<TEntity> GetAsyncEnumerator(CancellationToken cancellationToken = default)
{
    return new FakeDbAsyncEnumerator<TEntity>(this.AsEnumerable().GetEnumerator());
}
```
-Sean

**Comment by slee-accesso** [comment]
In further research, it appears that the class it is inheriting from is now using an interface, not an abstract or virtual method. So - the only thing that needs to happen is the removal of the "override".

**Comment by slee-accesso** [comment]
This was my fault. I had the EF 5 nuget packages installed. Switching to EF 6 fixed them. Sorry for the trouble.

**Comment by sjh37** [comment]
Lol no problem Sean. Glad you figured it out.
