### ISSUE TITLE
Connectionstring in tt file

### ISSUE THREAD

**Issue by NeilN1** [sjh37/efreversepoco#766]
I'm using DI in .NET 6 and have Settings.OnConfiguration = OnConfiguration.Omit; so the connection string does not appear in the generated classes. But how do people handle the connection string appearing in plaintext in the tt file when pushing code to a repository?

**Comment by sjh37** [comment]
There are a few ways. Have a read of these two articles.

- https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/Settings.OnConfiguration#settingsonconfiguration--onconfigurationomit
- https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/ConnectionString

**Comment by NeilN1** [comment]
I did read both articles before posting. Am I correct in thinking that only the second applies to the .tt file and I would have to manually change the environment variable every time I switch to a branch that connects to a different version of the database?

**Comment by sjh37** [comment]
Hi Neil. Thanks for reading 👍 
The second is only used for uat/production environments, and not for development as you can chop and change all the time.
I personally go for `Settings.OnConfiguration = OnConfiguration.ConnectionString` for local development. The connection string is usually something simple like

```cs
.UseSqlServer(@"Data Source=(local);Initial Catalog=Northwind;Integrated Security=True;MultipleActiveResultSets=True");
```

However, for your needs, in `startup.cs` add in

```cs
services.AddDbContext<BackOfficeContext>(options =>
{
     options.UseSqlServer(Configuration.GetConnectionString("BackOffice"));
});
```
or
```cs
var defaultConnection = this.Configuration.GetConnectionString("DefaultConnection");
services.AddDbContext<BackOfficeContext>(options =>
    options.UseSqlServer(defaultConnection));
```


For an Azure function, you can pick it up from environment
```cs
class Startup : FunctionsStartup
{
    public override void Configure(IFunctionsHostBuilder builder)
    {
        var sqlConnection = Environment.GetEnvironmentVariable("SQL_CONNECTION");
        builder.Services.AddDbContext<BackOfficeContext>(
            options => options.UseSqlServer(sqlConnection));
    }
}
```

**Comment by sjh37** [comment]
Your `appsettings.json` will have the local connection string, and in `appsettings.Production.json` you will have your production connection string, etc.
