### ISSUE TITLE
how to use version 3.6.0 in rider in mac?

### ISSUE THREAD

**Issue by vahidjavadinasab** [sjh37/efreversepoco#773]
can I use version 3.6.0 in rider mac?

**Comment by sjh37** [comment]
Hi @vahidjavadinasab 
Not out of the box as non-SDK style project files require `EF6.Utility.CS.ttinclude` which is incompatible with Rider.
However, I did create a repo [EfrpgRider](https://github.com/sjh37/EfrpgRider) that works with Rider, so use that.

I would use VS2022 Community to run the generator and, once generated, switch back to using Rider.

**Comment by vahidjavadinasab** [comment]
Thank you very much.🙏

**Comment by vahidjavadinasab** [comment]
Hi @sjh37  , after installing Mono.framework, I was able to run it on Mac.
Of course, I made some minor changes.
Version 3.6.0
