### ISSUE TITLE
Wiki: Table Per Type, EF core

### ISSUE THREAD

**Issue by fasteddys** [sjh37/efreversepoco#775]
Hello Simon, I am trying to learn your cool tool, my goal is to see if I can use it regularly to reverse the DB; make updates to the DB tables; and then reflect those chance back to the DB.

I tried the this so far, I first reversed an pre/existing db table ->`Engine` table. Second, in my middleware I added new inherited objects like `Car`, `Auto`, `Rickshaw`  which `inherit` from my `Engine Poco`, I dont know how to do t`able per types` with your tool and persist them back to DB?

Can you please help, I searched your wiki and was not able to find my way, _in your code how do I do the following_ 

1. How to `setup/add/update/enhance`  `Table Per Type` or Hierarchy, with inherited types in my middleware, for e.g. `Engine `-> inside  **ReversePOCO** how can I setup the new models  `Car`, `Auto`, `Rickshaw` etc. as Table per Types

2. Once I make those changes, how do I reflect the new updates from the Reverse Poco Model to the database? is there an some switch or option to run `add-migration`; and `update database,` from **ReversePOCO** once I make the updates, or is something I have to do manually outside?

**Comment by sjh37** [comment]
Hi @fasteddys 
You are using the tool incorrectly. The changes should be made first to the database directly, using `CREATE TABLE` etc. Then simply press Save (ctrl-s) on your `<database>.tt` file and that will create your new POCOs for you automatically. 

Each time the database is changed, press save on your .tt file to have the generator create the classes you need.

This generator reads the database schema and creates POCOs for you. It does not work the other way around where it creates tables in the database.

**Comment by fasteddys** [comment]
Thanks @sjh37 
I was able to generate the Poco, but how do I refactor the generated to look like TPer type concrete tables.
