### ISSUE TITLE
Enum from tables and replace props referencing it

### ISSUE THREAD

**Issue by McDoit** [sjh37/efreversepoco#777]
I'm trying to achieve a workflow where i generate Enums from tables, find props in entities having a FK there and repalce the prop with the enum and then remove the navigation property from that entity

So a bit like this:

Table api.Types into a enum type like this (with `AddEnum`)
```cs
public enum ApiTypesEnum
{
        Facebook = 1,
        Instagram = 2,
}
```

and turn entity for table api.Users
```cs
public class ApiUserEntity
{
        public int Id { get; set; } // ID (Primary key)
        public int ApiTypeId { get; set; } // FKApiTypeID

        public virtual ApiTypeEntity ApiUserType { get; set; } // FK__Users__FKApiTyp__72D05FB5
}
```
into this
```cs
public class ApiUserEntity
{
        public int Id { get; set; } // ID (Primary key)
        public ApiTypesEnum ApiTypeId { get; set; } // FKApiTypeID
}
```

As the enum tables are just there for db constraints and dont want them as a navigation property

My problem is that `AddEnum` is called after `UpdateColumn `and similar calls, so I cant use the enums i generate in `AddEnum`
And a problem I have is that the `FkEntity` property on column is empty, dunno if it is related to some other changes I made

Is there any better or other way to achieve this that I have missed?

**Comment by sjh37** [comment]
Hi Erik,

The following callback should help you:

```cs
// Use the following list to replace column byte types with Enums.
// As long as the type can be mapped to your new type, all is well.
Settings.AddEnumDefinitions = delegate(List<EnumDefinition> enumDefinitions)
{
    enumDefinitions.Add(new EnumDefinition { Schema = "dbo", Table = "ApiTypes", Column = "Id", EnumType = "ApiTypesEnum" });
};
```

**Comment by McDoit** [comment]
But then I can't use automatic filtering/adding of Enums as in `AddEnum` from a `Table`

Best would be to be able to add `EnumDefinition` from the tables targeting a `Table` i want defined as an `Enum`

But i don't know if its possible in how the script currently work, and the order parts are executed

**Comment by McDoit** [comment]
@sjh37 I can kinda work around it, but then I need to have some extra Lists to temp store data in between the calls
What wold be the best way to do that? As it is now, if I define var `enumTables = new List<string>();` it doesn't seem to be accessible from other delegates?

**Comment by sjh37** [comment]
You could add an enumTables list to the `Settings` class located at the top of the `EF.Reverse.POCO.v3.ttinclude` file.
I'll have a play and report back.

**Comment by sjh37** [comment]
Add `EnumTables` to the top of the settings class like so:

```cs
public static class Settings
{
    public static List<string> EnumTables = new();
    ...
}
```

And you can use that anywhere in your <database>.tt file like so:

```cs
Settings.EnumTables.Add("todo");
```

**Comment by sjh37** [comment]
I will close this issue. Any problems, please let me know here.
