### ISSUE TITLE
Filter Sequences created

### ISSUE THREAD

**Issue by MarkLFT** [sjh37/efreversepoco#780]
My database contains a number of sequences, several that are not required by EF Core, is their a way to filter which sequences are defined in the  OnModelCreating method?

**Comment by sjh37** [comment]
Hi Mark, Nothing as yet.
However, knowing which ones to keep can be automatically detected by looking at the (poorly and soon to be renamed) `column.HasDefaultValueSql`.

This is a quick win, and I may get to it this week.

**Comment by sjh37** [comment]
Hi @MarkLFT  This is now complete and will be in the next release. If you want it now, grab the [EF.Reverse.POCO.v3.ttinclude](https://raw.githubusercontent.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/48692a68fb5c5d7bfec9b46f239928fe3ec9e346/EntityFramework.Reverse.POCO.Generator/EF.Reverse.POCO.v3.ttinclude) file.

**Comment by sjh37** [comment]
Released in v3.8.1
