### ISSUE TITLE
C# 11 Compiler warning C8981 for dtproperty

### ISSUE THREAD

**Issue by baldvinhansson** [sjh37/efreversepoco#784]
After updating to C# 11 the generator will produce code resulting in a C8981 compilation warning for public partial class dtproperty. Is there a way to have the generator choose a different name for this class or somehow prevent this warning from occurring without either disabling the C8981 warning or manually renaming the class to something like DtProperty, dtProperty etc. each time the generator runs?

**Comment by sjh37** [comment]
Hi @baldvinhansson 
You can rename tables in your <database>.tt file. Look at the callback `Settings.TableRenam` at approximately line 275. You should see some commented out examples there.
