### ISSUE TITLE
Versionnumber in GeneratedCode attribute

### ISSUE THREAD

**Issue by erwin-faceit** [sjh37/efreversepoco#796]
The full version is included in the GeneratedCodeAttribute, which results in updating a lot of files when actually nothing is changed. To me, this pollutes Git history with changes that don't have an impact on the code, but makes finding changes very difficult (especially when one of your projects has over 800 POCO classes :scream:).

I would propose to decorate the Entities class with the full version, but the POCO classes just with the major version.

For the POCOS:

```C#
[GeneratedCode("EF.Reverse.POCO.Generator", "3.0.0.0")]
```

and for the Entities class:

```C#
[GeneratedCode("EF.Reverse.POCO.Generator", "3.8.1.0")]
```

**Comment by sjh37** [comment]
How about turning off that attribute with:

```cs
Settings.IncludeGeneratorVersionInCode = false;
```

**Comment by erwin-faceit** [comment]
Give me the dunce hat, so I can stand in the corner shaming myself…

Thanks for the pointer though 👍
