### ISSUE TITLE
Reading ConnectionString from Key Vault 

### ISSUE THREAD

**Issue by rajukumar-jha** [sjh37/efreversepoco#798]
Hi @sjh37 Is there any way to replace reading the Setting.ConnectionString from appsettings.Development.json to Key Vault? Please share your thoughts. Thank You

**Comment by sjh37** [comment]
Yes, you are in complete control of your reading your connection string from anywhere you like, including Key Vault.

Have read of [simple-configuration-of-connection-string-through-key-vault](https://www.c-sharpcorner.com/article/simple-configuration-of-connection-string-through-key-vault2/) and [stackoverflow](https://stackoverflow.com/a/61791016/5884)

However I don't use it and prefer to set the connection string on the web app:
![image](https://user-images.githubusercontent.com/4190514/225280817-2cd847df-4883-4dbf-b528-65545b461be4.png)

I use this. In `Startup.cs`, ConfigureServices function, this is what I have:
```cs
services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

...

services.AddTransient<IApplicationDbContext, ApplicationDbContext>();
```

`appsettings.json`
```json
{
  "ConnectionStrings": {
    "DefaultConnection": "Server=localhost;Database=ReversePoco;Integrated Security=true"
  },
  "AllowedHosts": "*"
}
```

`appsettings.Production.json`
```json
{
}
```

**Comment by rajukumar-jha** [comment]
Thank You @sjh37 for your prompt response. However, I would like to know the implementation by editing the .tt & .ttinclude files. I already have the license for Reverse POCO Generator. Editing the .tt & .ttinclue files helps us in customizing our application architecture. Now that we have a requirement that instead of reading the DefaultConnection from appsettings.json we have to integrate Key Vault so that connectionString value can be fetched from there. Need you comments on this. Thank You

**Comment by sjh37** [comment]
In `Program.cs` you should have the following
```cs
var environment = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")
                  ?? Environments.Development;
Console.WriteLine($"EnvironmentName = {environment}");

var configuration = new ConfigurationBuilder()
    .AddJsonFile("appsettings.json", false, true)
    .AddJsonFile($"appsettings.{environment}.json", true, true)
    .AddEnvironmentVariables()
    .Build();
```

Notice that it loads `appsettings.json` first, then adds `appsettings.Production.json`, then adds your `environment variables`.
It's the "environment variables" that are key here, as that is what Azure sets for you in the screenshot with configuration above.

When **developing** locally on your laptop the connection is read from the `appsettings.json` file, then overwritten with the `appsettings.Development.json` file.

In **production**, the connection is read from the `appsettings.json` file, then overwritten with the `appsettings.Production.json` file, then overwritten with the `environment variables` set by Azure configuration above.

**Comment by sjh37** [comment]
If you want to use KeyVault the same way as the above examples show, then have a read of [key-vault-configuration](https://learn.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-7.0)

Code examples are plentiful on GitHub. just search for "connectionstring AddAzureKeyVault UseSqlServer"

- https://github.com/sinbaddoraji/IrisMed/blob/25d35f97de09b6fac2c256352f7b13815df04015/IrisMed/Program.cs
- https://github.com/jstadnicki/isthereanynews/blob/b73419e3e44d9767d60d3ee3062131771ae49345/Itan.Database/DesignTimeDbContextFactory.cs
- https://github.com/Azure-Samples/todo-csharp-sql/blob/786abc653d4da12a3f505bd76906cbc0bd68b675/src/api/Program.cs
