### ISSUE TITLE
How to read connection string from user secrets in database.tt file.

### ISSUE THREAD

**Issue by SatishPaiB** [sjh37/efreversepoco#799]
Hi @sjh37  Is there any way, instead of reading the direct connection string in the database.tt, I can use user secrets to get the connection string. 

![image](https://user-images.githubusercontent.com/20751784/225704145-f7974fc5-31d8-4c34-bab8-fa35d50a09a0.png)

instead of connnecting string, I can write code, such as extracting the value from user secerts such as what we write in startup.cs or program.cs.

![image](https://user-images.githubusercontent.com/20751784/225705090-34dfce9f-d0f9-4122-bf27-fa8cfdac6273.png)

It will be helpful if you give me something in asp.net 6.0.

Thank you very much.

**Comment by sjh37** [comment]
Hi, Take a look at #798

**Comment by sjh37** [comment]
I got it working with setting an environment variable `conn` to my connection string.
![image](https://user-images.githubusercontent.com/4190514/225873555-8472c190-c7f6-4ef8-8bd9-b1404fbb100f.png)

And using the following in `<database>.tt`

```cs
Settings.ConnectionString = Environment.GetEnvironmentVariable("conn", EnvironmentVariableTarget.User);
```

**Comment by sjh37** [comment]
Just realised I already had a wiki article on it here: [wiki - ConnectionString](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/ConnectionString)

**Comment by SatishPaiB** [comment]
@sjh37  thank you very much.
