### ISSUE TITLE
No release notes for 3.8.1?

### ISSUE THREAD

**Issue by nealculiner** [sjh37/efreversepoco#801]
Trying to review what's changed but don't see a 3.8.1 version listed.

**Comment by sjh37** [comment]
Hi @nealculiner https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/releases

**Comment by nealculiner** [comment]
@sjh37 the latest I see is 3.8.0.

**Comment by sjh37** [comment]
Sorry, it was marked as `draft`. All sorted now :-)
