### ISSUE TITLE
EF Core Breaking Change - Mitigation

### ISSUE THREAD

**Issue by MarkLFT** [sjh37/efreversepoco#802]
Do you have any plans to add the mitigation for the workaround in the latest version of EF Core for tables with computed fields that use Functions()?   [https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes#sql-server-tables-with-triggers-or-certain-computed-columns-now-require-special-ef-core-configuration](url)

We have several legacy databases which we are slowly migrating to micro-services and EF Core, but a reasonable number of these tables contain convenience fields that use computed fields which contain scalar functions.  In the latest release of EF Core, saving a record to these tables fails. 

There is a mitigation which we manually add to the entity configuration currently, until we can look at all the computed fields.  But I was wondering if this is something we could include in this generator?  i.e. for tables that contain a computer field, and only those tables, force the old-style saving. That way I wouldn't miss any. ;-)

**Comment by sjh37** [comment]
Hi Mark,
v3.8.0 added `.HasTrigger()` for tables with triggers for EF Core 7. I missed the info about doing the same for computed columns! Thanks for bringing this to my attention, completely missed it. I'll get that added.

**Comment by sjh37** [comment]
This will be in the next release v3.8.2 which will be later today.

**Comment by sjh37** [comment]
This has been released in v3.8.2. Any problems, please let me know.

**Comment by MarkLFT** [comment]
Hi Simon,

Just wanted to say a huge thank you for your great support on this product.
