### ISSUE TITLE
EF6 - Stored Procedures with TableValueParams - I[DbContext] not including System.Data.DataTable

### ISSUE THREAD

**Issue by GregBartlett** [sjh37/efreversepoco#805]
I just upgraded from 2.x to 3.8.3 on our project, and it appears that when it's generating the I[DbContextName] interface it's missing the System.Data (so that the params that are generated in the code that have DataTable types will be referenced correctly)

I'm generating code for EF6 and have numerous tables with TVP's. 
Did I miss a configuration change somewhere?

Thanks and love the product!

**Comment by sjh37** [comment]
Hi @GregBartlett 

This should be fixed now. Grab the latest [EF.Reverse.POCO.v3.ttinclude](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/blob/master/EntityFramework.Reverse.POCO.Generator/EF.Reverse.POCO.v3.ttinclude) and update your project. Let me know if you have issues and I'll re-open this case.

**Comment by GregBartlett** [comment]
Thanks for the quick fix! Confirmed I'm no longer having the issue.

**Comment by sjh37** [comment]
Released v3.8.4
