### ISSUE TITLE
Add "IsSynonym" property to Table class

### ISSUE THREAD

**Issue by grantparker77** [sjh37/efreversepoco#819]
Please add a `IsSynonym` property to the Table class in EF.Reverse.POCO.v3.ttinclude.  We need to know if the object is a table, view, or synonym.  It does not appear there is any way to know if the object is a synonym or not.

**Comment by sjh37** [comment]
This will be in the next release.

**Comment by sjh37** [comment]
p.s. If you want the code now, grab the latest .ttinclude file and copy over your existing file in your project.
[EF.Reverse.POCO.v3.ttinclude](https://raw.githubusercontent.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/master/EntityFramework.Reverse.POCO.Generator/EF.Reverse.POCO.v3.ttinclude)

**Comment by grantparker77** [comment]
Thank you!
