### ISSUE TITLE
Table wich name contains a dot gets ignored

### ISSUE THREAD

**Issue by fguemara** [sjh37/efreversepoco#826]
Hello,

Some of my origin database tables are named with a dot : `[dbo].[abc.xyz]` and they are getting ignored by the generator.
How can I indicate it to reverse poco, knowing that I cannot change the table name ?

```cs
Settings.GeneratorType = GeneratorType.EfCore;
Settings.DatabaseType = DatabaseType.SqlServer;
```

Thanks a lot, great tool by the way.

Cheers
Fayçal

**Comment by sjh37** [comment]
Resolved. This will be in the next release. 
Replace your projects `EF.Reverse.POCO.v3.ttinclude` file with this latest code from [EF.Reverse.POCO.v3.ttinclude](https://[raw.githubusercontent.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/master/EntityFramework.Reverse.POCO.Generator/EF.Reverse.POCO.v3.ttinclude](https://raw.githubusercontent.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/master/EntityFramework.Reverse.POCO.Generator/EF.Reverse.POCO.v3.ttinclude))
