### ISSUE TITLE
Upgrade from v3.X.X to v3.Y.Y

### ISSUE THREAD

**Issue by mrmyroll2** [sjh37/efreversepoco#839]
What's the most efficient approach for updating versions, like transitioning from `v3.8.4` to `v3.9.0`?
Currently, I updated the extension in Visual Studio and then replaced the old `[DB].tt` and `EF.Reverse.POCO.v3.ttinclude` files. Next, I manually compared the `[DB].tt` with the previous setup like connection string etc.
However, I'm seeking a more efficient approach.
Hopefully you can also shared it on the `README.md`

**Comment by sjh37** [comment]
Hi @mrmyroll2 
I've a very simple wiki page on it here: [Upgrading Version](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/Upgrading-version)

**Comment by mrmyroll2** [comment]
Thanks for your reply. It's working, but there's another issue: we might be missing out on new features because I'm still using the `old.tt` file. I've noticed some differences between the `old.tt` and `new.tt` files, which could mean I'm not seeing all the latest settings.

Maybe can try the old version's method with a `config` file, or even switch to a `json` file. This might not only cover the connection string but also other setup options. Just a thought; not sure if it's feasible with the current version. 😅
