### ISSUE TITLE
POCO  Generator from MSSQL Server to Postgress Compatible classes ?

### ISSUE THREAD

**Issue by wilz055** [sjh37/efreversepoco#846]
Is there anyway we can generate codes  from MSSQL to postgres sql. I could not get any instructions for the same. 

For example : I have MSSQL Server which has tables and functions triggers sp's 
I want to generate Class models for Postgres db. any documentations or configurations settings  you can share.

@sjh37

**Comment by sjh37** [comment]
Hi @wilz055 
Take a look at the [postgres wiki](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/wiki/PostgreSQL). This explains how I did it.
